### ISSUE TITLE
talentdeficit - Unchecked dependencies

### ISSUE THREAD

**Issue by ascrookes** [slogsdon/mandrill-elixir#10]
When I include this project in my `mix.exs` I get an unchecked dependency error.
Any thoughts on how to fix this or why it might be happening? I am running Elixir 1.1.1
Below is the full error from when I execute `mix compile`

```
Unchecked dependencies for environment dev:
* jsx (git://github.com/talentdeficit/jsx.git)
  lock outdated: the lock is outdated compared to the options in your mixfile (run "mix deps.get" to fetch locked version)
** (Mix) Can't continue due to errors on dependencies
```

**Comment by slogsdon** [comment]
Sorry for the delay, @ASCrookes! This usually happens when the `mix.exs` and `mix.lock` files are out of sync for whatever reason. Let me look into this to see what's going on with them.

**Comment by ASCrookes** [comment]
No worries about the delay! Any info @slogsdon

**Comment by slogsdon** [comment]
I've been trying to replicate this in local projects, but I haven't yet been successful.

Just to be sure, you have tried running `mix deps.get` in your project, correct?

**Comment by ASCrookes** [comment]
Hey, sorry about the delayed response. I have since switched from using mandrill for my project (for other reasons) so I'm not sure. It easily could've just been an issue with my specific setup if you can't recreate it.
