### ISSUE TITLE
Publish mandrillex to Hex.pm

### ISSUE THREAD

**Issue by guilleiguaran** [slogsdon/mandrill-elixir#2]
More: https://hex.pm/docs/publish

**Comment by orendon** [comment]
Thanks for putting this live @slogsdon!

Btw, It seems to be duplicated on hex.pm
https://hex.pm/packages/mandrill
https://hex.pm/packages/mandrillex

**Comment by slogsdon** [comment]
@orendon Yep, it is. I had renamed the package a while back, but I didn't want to interfere with users of the older package name/versions.
